//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room.DataSources.Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public string ROOM_ID { get; set; }
        public string ROOM_NAME { get; set; }
        public Nullable<byte> STUD_CAPACITY { get; set; }
        public Nullable<byte> EXAM_CAPACITY { get; set; }
        public string ROOM_TYPE { get; set; }
        public string ROOM_ACCESSORY { get; set; }
        public string BUILDING_ID { get; set; }
    }
}
