//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public string ROOM_ID { get; set; }
        public string ROOM_NAME { get; set; }
        public string ROOMTYPE_ID { get; set; }
        public Nullable<int> size { get; set; }
        public string ROOM_IMAGE { get; set; }
        public string BUILD_ID { get; set; }
        public string ROOM_NOTE { get; set; }
        public string ADMIN_ID { get; set; }
        public string PRICE_ROOM { get; set; }
    }
}
