//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class reservation_systemEntities : DbContext
    {
        public reservation_systemEntities()
            : base("name=reservation_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<room> rooms { get; set; }
    
        public virtual ObjectResult<sp_room_Result> sp_room(string pRoomId)
        {
            var pRoomIdParameter = pRoomId != null ?
                new ObjectParameter("pRoomId", pRoomId) :
                new ObjectParameter("pRoomId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_room_Result>("sp_room", pRoomIdParameter);
        }
    }
}
